name: cookies
version: 0.0.3
description: Cookie Parser
author: T. Jameson Little <beatgammit@gmail.com>
homepage: https://github.com/beatgammit/dart-cookies
dependencies:
dev_dependencies:
  unittest: any
